sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      env: TARGET=linux_x86_64
    - os: linux
      env: TARGET=linux_i686
    - os: linux
      env: TARGET=linux_armv7l
    - os: linux
      env: TARGET=linux_aarch64
    - os: linux
      env: TARGET=windows_x86
    - os: linux
      env: TARGET=windows_amd64
    - os: osx
      env: TARGET=darwin

before_script:
  - if [[ ${TARGET:0:7} == "windows" ]]; then sudo dpkg --add-architecture i386; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi

script:
  - bash build.sh $TARGET
  - openssl sha1 _packages/**/*.tar.gz

deploy:
  provider: releases
  api_key:
    secure: m8SNdlWdsN4XdCI5B5fExK54kMBHGcex0KnKW7EOQJN64ndGQ4PiE3ORAprMvrMVHhmTYWvBd2Kr7WguSt0HHqE3vf8hq58OHa7pfdfqX7PRqdGZ47IauLKPWmv/Cq7hm/y5taCl0OBXZVWQc4Dr3/8g48lzsiJUalnhjPlpt8IVFUDlWQqWUtp1C7Pr2qT7N6jMMTL5aZQS2RmdDXexvt2kpfgMP2kKNSeVmE5zyZlhr0VB+qWMp0jQdMX1FU3ebW9F7zc7onsgK5t52PdRu6Q8BiZ22Mq4q98ClatxZjwOtfZkbdy7O8JI6gFCKqAMdqmmbOVjleECyJghCQl2huneeWJINAGPa50bNt9Aoy6+hwGBT2iN2MxhOIOk1WcacZsnwdynTK7QKLSUYgfHZIa1ROAtIEnNXiSD03OchO4XeQde9rl8ZWEAXuV8m1JF+bNysut+HElXsLjzS7IL1yP/U79ylo7ozGF4uyVxrwRf1Fxzji0TjaQO5tdsF5cB0LHJ3H422uT+XTilzQ+rczakoPQgaSbOPUfwrVd2EN1XSknEsrpZ/otntd6JA20pmz1zENodouAeRMee7KoRE5bOuiRpDQ3iEKISUhCgnPxZ06scKFERSmHg16UY/KxkCBJ8QYhVBv/kbzXVGzO1B6E2lZWM0izggJ002lcoQpY=
  file:
    - _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
